FROM python:3.12

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV TZ=Asia/Bangkok

# Set work directory
WORKDIR /app

# Copy only the requirements.txt first to leverage Docker cache
COPY ./share/requirements.txt /app/
# install (and, optionally)
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt

# Now copy the rest of your code
COPY ./share/* .

# Copy shared directories
COPY ../share/data/ ./data/
COPY ../share/settings/ ./settings/
COPY ../share/core/ ./core/
COPY ../share/utilities/ ./utilities/
COPY ../share/middlewares/ ./middlewares/

# Copy project
COPY ./fastapi-ai-chat .